FROM ghcr.io/pytorch/pytorch-nightly:b3874ab-cu11.8.0

ARG HK_TOKEN

WORKDIR /src

RUN apt-get update && \
    apt-get install -y git git-lfs && \
    git lfs install

RUN git clone https://huggingface.co/datasets/lingjoor/lingjoor-dataset && \
    git clone https://github.com/kunato/axolotl

WORKDIR /src/axolotl

RUN pip install packaging && \
    pip install -e '.[deepspeed]' && \
    pip install flash-attn==2.3.2 && \
    pip install -U git+https://github.com/huggingface/peft.git && \
    pip install transformers_stream_generator

COPY scripts/train.sh /src/scripts/
COPY configs /src/configs/

# Run the server
CMD ["sh", "../scripts/train.sh", "-t", "$HK_TOKEN"]
