FROM ghcr.io/pytorch/pytorch-nightly:b3874ab-cu11.8.0

# Set the working directory in the container to /src
WORKDIR /src

RUN apt-get update && apt-get install -y git

COPY ./utils/ /src/utils
COPY ./training_requirements.txt /src/training_requirements.txt

# Install any needed packages specified in requirements.txt that come from lit-gpt
RUN pip install --no-cache-dir --upgrade -r training_requirements.txt

# Run the server
CMD ["python", "-m", "utils.data_pipeline.process"]
